### ISSUE TITLE
ReferenceError: xdescribe is not defined

### ISSUE THREAD

**Issue by JakeSidSmith** [yandex/mocha-parallel-tests#102]
I've used mocha-parallel-tests on a personal project before now and was pleased with the performance, so I decided to drop it into a project at work.

I didn't realise it was a thing until just now, but apparently you can use `xdescribe()` to completely skip a group of tests (as one of my colleagues has), it's an alias for describe.skip. Mocha-parallel tests however does not seem to handle this.

Source: https://github.com/mochajs/mocha/blob/2bb2b9fa35818db7a02e5068364b0c417436b1af/lib/interfaces/bdd.js#L55

**Comment by 1999** [comment]
@JakeSidSmith thank you for your story. Right now you can use `*.skip` methods in mocha-parallel-tests: all of them are supported. But we will try to add `x*` as well.

@k03mad your turn :)

**Comment by JakeSidSmith** [comment]
I have already switched to `describe.skip`. Just thought you guys would want to know. :)

**Comment by 1999** [comment]
Sure. Thank you!

**Comment by k03mad** [comment]
By the way, this minor edits adds support for xit/xdescribe:
https://github.com/yandex/mocha-parallel-tests/pull/103

(I think 😃 )

**Comment by 1999** [comment]
mocha-parallel-tests=1.2.7
