### ISSUE TITLE
Installation error occurred while install on local (windows)

### ISSUE THREAD

**Issue by dharmakrish6** [yandex/mocha-parallel-tests#111]
**Command**
`npm install --save-dev mocha-parallel-tests mocha
`
**Error Log**
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dharma\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "mocha-parallel-tes
ts" "mocha"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.2

npm ERR! Unexpected token D in JSON at position 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by 1999** [comment]
@dharmakrish6 thank you for the issue. Currently mocha-parallel-tests was not tested on windows. However we have plans for this: #109

**Comment by 1999** [comment]
Should be fixed now.
