### ISSUE TITLE
mochawesome reporter not supporting 

### ISSUE THREAD

**Issue by dharmakrish6** [yandex/mocha-parallel-tests#113]
`mocha-parallel-tests --reporter mochawesome <test-folder>`

mochawesome report not supported by mocha-parallel-tests. Please tell which reporter it will support

**Comment by 1999** [comment]
@dharmakrish6 thank you for posting issue. Currently mocha-parallel-tests supports all mocha native reporters and experimentally some of the custom (look https://github.com/yandex/mocha-parallel-tests/tree/master/test for "reporter"). I will try to take a look at this.

**Comment by 1999** [comment]
However I can't see the reason for this reporter to not work. Can you send example of the output and what's not working in your case?

**Comment by iamcxy** [comment]
Here's the stack-trace:

/usr/local/lib/node_modules/mocha-parallel-tests/dist/lib/reporter.js:124
            throw new Error(`Invalid reporter "${this._options.reporterName}"`);
            ^

Error: Invalid reporter "mochawesome"
    at AbstractReporter._setReporterOnce (/usr/local/lib/node_modules/mocha-parallel-tests/dist/lib/reporter.js:124:19)
    at new AbstractReporter (/usr/local/lib/node_modules/mocha-parallel-tests/dist/lib/reporter.js:84:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:501:18)
    at scheduleMochaRun (/usr/local/lib/node_modules/mocha-parallel-tests/dist/lib/watcher.js:253:30)
    at runTestsRecursive (/usr/local/lib/node_modules/mocha-parallel-tests/dist/lib/watcher.js:318:29)
    at exports.runTests (/usr/local/lib/node_modules/mocha-parallel-tests/dist/lib/watcher.js:355:5)
    at binHelper (/usr/local/lib/node_modules/mocha-parallel-tests/dist/bin-helper.js:132:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha-parallel-tests/dist/bin/mocha-parallel-tests:26:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by 1999** [comment]
Are you sure that you have `mochawesome` installed alongside with mocha-parallel-tests? Is it installed globally? Do you run your tests on windows?

**Comment by 1999** [comment]
@iamcxy ^

**Comment by iamcxy** [comment]
@1999  tests are ran on linux env. mochawesome and mocha-parallel-tests are both defined in projects' package.json file, not globally. It seems that mocha-parallel-tests only support out of package mocha reporters:
    dot - dot matrix
    doc - html documentation
    spec - hierarchical spec list
    json - single json object
    progress - progress bar
    list - spec-style listing
    tap - test-anything-protocol
    landing - unicode landing strip
    xunit - xunit reporter
    min - minimal reporter (great with --watch)
    json-stream - newline delimited json events
    markdown - markdown documentation (github flavour)
    nyan - nyan cat!

but not mochawesome. However if run the tests with only mocha, mochawesome reports could be generated.

**Comment by 1999** [comment]
> It seems that mocha-parallel-tests only support out of package mocha reporters:

That's not right. I double-checked this and there's a problem with support for mochawesome. I will try to find the reason for this asap.

![image](https://cloud.githubusercontent.com/assets/73191/25655083/fee7d936-3036-11e7-8b1a-90b40f4ca41c.png)

**Comment by iamcxy** [comment]
Thanks! @1999

**Comment by 1999** [comment]
Okay, it seems like there's one more internal mocha API which I missed. Currently we support callback with failures number but not the done() callback.
```javascript
function done (failures) {
    if (reporter.done) {
      reporter.done(failures, fn);
    } else {
      fn && fn(failures);
    }
  }

  return runner.run(done);
}
```

**Comment by 1999** [comment]
@iamcxy mocha-parallel-tests=1.2.9 contains this fix
https://github.com/yandex/mocha-parallel-tests/commit/6058b2fb2dd47269445638704651158beb6f2edb

**Comment by dharmakrish6** [comment]
Still same error
```
+-- mocha@3.3.0
`-- mocha-parallel-tests@1.2.9
```


$mocha-parallel-tests --reporter mochawesome ./test
C:\Users\dharma\AppData\Roaming\npm\node_modules\mocha-parallel-tests\dist\lib\r
eporter.js:128
            throw new Error(`Invalid reporter "${this._options.reporterName}"`);

            ^

Error: Invalid reporter "mochawesome"
    at AbstractReporter._setReporterOnce (C:\Users\dharma\AppData\Roaming\npm\no
de_modules\mocha-parallel-tests\dist\lib\reporter.js:128:19)
    at new AbstractReporter (C:\Users\dharma\AppData\Roaming\npm\node_modules\mo
cha-parallel-tests\dist\lib\reporter.js:84:14)
    at Mocha.run (C:\Users\dharma\AppData\Roaming\npm\node_modules\mocha\lib\moc
ha.js:501:18)
    at scheduleMochaRun (C:\Users\dharma\AppData\Roaming\npm\node_modules\mocha-
parallel-tests\dist\lib\watcher.js:253:30)
    at runTestsRecursive (C:\Users\dharma\AppData\Roaming\npm\node_modules\mocha
-parallel-tests\dist\lib\watcher.js:318:29)
    at exports.runTests (C:\Users\dharma\AppData\Roaming\npm\node_modules\mocha-
parallel-tests\dist\lib\watcher.js:355:5)
    at binHelper (C:\Users\dharma\AppData\Roaming\npm\node_modules\mocha-paralle
l-tests\dist\bin-helper.js:132:27)
    at Object.<anonymous> (C:\Users\dharma\AppData\Roaming\npm\node_modules\moch
a-parallel-tests\dist\bin\mocha-parallel-tests:37:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by 1999** [comment]
@dharmakrish6 I double-checked this on my mac and it's working. May be related to windows, since currently mocha-parallel-tests is not windows-tested. Can you clone this gist and run tests from README on your computer? https://gist.github.com/1999/9ea881310f33f47aefb23bb32a8996c8

**Comment by dharmakrish6** [comment]
@1999 .Now report generated, But the Report is empty. Are you able to view the Mochawesome html report ?

**Comment by dharmakrish6** [comment]
@1999 .It generates the report but html is empty . usually the mochawesome will create `mochawesome-reports` for reports . But when i run with mocha-parallel-test, it creates `mochawesome-report` . HTML report is empty

**Comment by dharmakrish6** [comment]
@1999 Not fetching all the details from the test to generate report.

**Comment by 1999** [comment]
Okay, I found the reason for this. Runner in mocha and runner in mocha-parallel-tests contain different suites. This is about mocha:

![image](https://cloud.githubusercontent.com/assets/73191/25744590/078d11ca-31de-11e7-882f-d9f134e1b150.png)

And this is about mocha-parallel-tests:

![image](https://cloud.githubusercontent.com/assets/73191/25744608/1c40b6f8-31de-11e7-8a65-36579b7dd367.png)

Probably the reason for this is that suites are all inside runner for mocha and this is kinda different for mocha-parallel-tests. Anyway, this is another bug and it's a blocker for this one. I will create a separate issue for that.

**Comment by kiran-z** [comment]
It seems data generated by mocha-parallel-tests is not correct.
for instance it shows pass percent as null  below.

```  "stats": {
    "suites": 105,
    "tests": 366,
    "passes": 366,
    "pending": 0,
    "failures": 0,
    "start": "2017-05-12T09:14:06.174Z",
    "end": "2017-05-12T09:15:30.503Z",
    "duration": 84329,
    "testsRegistered": 0,
    "passPercent": null,
    "pendingPercent": null,
    "other": 0,
    "hasOther": false,
    "skipped": -366,
    "hasSkipped": false,
    "passPercentClass": "success",
    "pendingPercentClass": "success"```

**Comment by 1999** [comment]
@kiran-z this is all about #115

**Comment by 1999** [comment]
@kiran-z thank you for pinging me. This thing was not fixed with 2.0.0 release however it was pretty easy to fix this now. I'm waiting for the last PR and then I will publish a 2.0.1 version which will contain the fix for `mochawesome` reporter as well. Should happen in 2-3 days, I will mention you here.

**Comment by 1999** [comment]
@kiran-z @dharmakrish6 @iamcxy sorry for a long wait. This issue is fixed in mocha-parallel-tests@2.0.1 which has just been published.

**Comment by kiran-z** [comment]
@1999 Thanks! will check it out.

**Comment by mpreethi90** [comment]
@1999 this is awesome. Thanks much !!

**Comment by dharmamoolya** [comment]
@1999 Great. thanks .

**Comment by dharmamoolya** [comment]
@1999 Report generated but the failed test data and other data is empty . 
![screen shot 2018-06-13 at 12 29 50 pm](https://user-images.githubusercontent.com/24267471/41335197-981c955c-6f05-11e8-880f-1bc5c32f57ab.png)

Refer above screenshot

**Comment by 1999** [comment]
@dharmakrish6 are you using custom steps in your tests?

**Comment by dharmamoolya** [comment]
Same test works with `macaca run ` But with `mocha-parrellel-tests` not generating `suites[]` data

**Comment by 1999** [comment]
@dharmamoolya not sure what's `macaca`. Can you answer the question above? If you don't use custom steps, can you please post your test here and `mocha-parallel-tests` that you're using as well as `mocha` version?

**Comment by mpreethi90** [comment]
Hey @1999 , just noticed that **mocha-parallel-tests + mochawesome** works fine for tests thats passing but for failed test I dont find even the **mochawesome-report** folder getting created

**Comment by 1999** [comment]
@mpreethi90 can you create a sample repo with reproducible example? I will take a look at it asap

**Comment by mpreethi90** [comment]
@1999  can you check https://github.com/mpreethi90/develop-Pre this sample repo?

STEPS to recreate:
1. Clone to the repo
2. cd to sample-nodejs-master
3. npm install 
4. npm run test:desktop-browser along with saucelabs username and key

I have made an expected failure by giving an invalid css element

**Comment by 1999** [comment]
Thank you @mpreethi90, I can reproduce this on your test:

![image](https://user-images.githubusercontent.com/73191/41640251-67a1bcf0-74a4-11e8-9434-6774dca873f1.png)

The problem is that there's no "end" event from the subprocess for some reason. I will take a look today.

**Comment by mpreethi90** [comment]
thanks for the prompt response ! awaiting for the fix.

**Comment by 1999** [comment]
Current status: I'm trying to find the reason why this happens only to this code. It looks like the problem occurs for all tests/libraries written with `q` promise library because not only does it have its own "unhandledRejection" handler but it also emits the "unhandledRejection" event on the next tick: https://github.com/kriskowal/q/blob/master/q.js#L1104

I'm investigating this further.

**Comment by kiran-z** [comment]
@1999 did a little bit of research on this.
 Issue seems to happen when an error occurs with all promise errors `UnhandledPromiseRejection` not specific to `q` promises.

**Comment by 1999** [comment]
I just created a separate issue #173 to track the progress of this bug instead of chatting in this closed issue. Hopefully it's okay
