### ISSUE TITLE
Miscellaneous errors

### ISSUE THREAD

**Issue by darobin** [yandex/mocha-parallel-tests#116]
I'm sorry to report these errors basically in a bundle: I can't seem to get a successful run of this module over my test suite, and as a result it is hard to figure out what exactly is causing these errors. If I can assist in narrowing down their triggering conditions, please simply ask.

On every start, I get:

```
(node:42017) Warning: Possible EventEmitter memory leak detected. 3 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
(node:42017) Warning: Possible EventEmitter memory leak detected. 7 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

If I set `--max-parallel` to `1`, the first error disappears. The second error is a function of `--max-parallel` as well: it always seems to be `2n + 3` (where `n` is `--max-parallel`). The `uncaughtException` one is always `3`, when it's there.

I also get:

```
TypeError: Cannot read property 'ended' of undefined
    at Pumpify.Writable.write (/Projects/SA/document-worker/node_modules/readable-stream/lib/_stream_writable.js:272:12)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:2004:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)
```

If I set `--max-parallel` to 3 or more, that error will occur right away, before any test runs. Otherwise it will happen at some later point in the suite, which does not seem to be clear but is dozens of tests later (so it doesn't seem to be because of a test running earlier due to increased parallelism).

Finally, there seem to be memory issues. When the latter test happens, not only are things already taking a lot longer than in the non-parallel case (3m30s vs 2m40s for the whole thing normally), but eventually this happens:

```
<--- Last few GCs --->

  208087 ms: Mark-sweep 1342.8 (1446.1) -> 1342.8 (1446.1) MB, 1021.6 / 0.0 ms [allocation failure] [scavenge might not succeed].
  209103 ms: Mark-sweep 1342.8 (1446.1) -> 1342.8 (1446.1) MB, 1015.5 / 0.0 ms [allocation failure] [scavenge might not succeed].
  210149 ms: Mark-sweep 1342.8 (1446.1) -> 1345.7 (1421.1) MB, 1046.0 / 0.0 ms [last resort gc].
  211208 ms: Mark-sweep 1345.7 (1421.1) -> 1349.9 (1416.1) MB, 1059.1 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x13bd946cfb51 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~129] [pc=0x2880e73748c2] (this=0x13bd94604381 <undefined>,w=0x13cec1576ec1 <JS Array[7]>,x=7,N=0x13bd946043c1 <true>,J=0x2a92fbfc1fd9 <String[6]\: ,\n    >,I=0x13bd946b46e1 <JS Function ConvertToString (SharedFunctionInfo 0x13bd94652dc9)>)
    2: Join(aka Join) [native array.js:180] [pc=0x2880e62eed12] (this=0x13bd94604381 <undefined>,w=0x13cec1576ec1...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/robin/.nvm/versions/node/v6.9.1/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/robin/.nvm/versions/node/v6.9.1/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/robin/.nvm/versions/node/v6.9.1/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Users/robin/.nvm/versions/node/v6.9.1/bin/node]
 5: v8::internal::Runtime_StringBuilderJoin(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/robin/.nvm/versions/node/v6.9.1/bin/node]
 6: 0x2880e14092a7
 7: 0x2880e73748c2
Abort trap: 6
```

My node is `v6.10.3`.

**Comment by 1999** [comment]
@darobin thank you for posting issue. That's kinda strange. How many test files do you have?

**Comment by darobin** [comment]
I have about 60. Some are pretty intense. One thing that may be related: almost all of them spawn processes at one point or another. Another potential indication: they all import a library that when constructed does (amongst other things):

```
    this._handleExit = once(this._handleExit.bind(this));
    process.setMaxListeners(process.getMaxListeners() + 2);
    process.on('uncaughtException', this._handleExit);
    process.on('exit', this._handleExit);
```

Normally this increases the maximum listeners enough to not get a warning, but it may be interacting.

**Comment by 1999** [comment]
@darobin  can you try mocha-parallel-tests@v2 and say if it's still a case for you?

**Comment by 1999** [comment]
Closing as non-answered after a week.
