### ISSUE TITLE
It does not accept --no-timeouts

### ISSUE THREAD

**Issue by furstenheim** [yandex/mocha-parallel-tests#119]
It is not able to use no-timeouts parameter

**Comment by 1999** [comment]
Thanks for posting this issue. I'm not sure what does this option do, because the docs are a bit mean here:

> disables timeouts, given implicitly with --debug

How do you actually use it?

**Comment by furstenheim** [comment]
Thanks for you quick reply. I use it mainly for long integration test where timeout is something more complicated than just a fixed number.

I will try to add it myself. I see that you are calling mocha here https://github.com/yandex/mocha-parallel-tests/blob/b8fd284a690e1b4942d0b2ff894eff94b9c332c7/lib/watcher.js#L80 but you don't seem to be passing any options.

**Comment by 1999** [comment]
Yep, if you can send a PR, that would be even better
