### ISSUE TITLE
Enable Greenkeeper for repo

### ISSUE THREAD

**Issue by 1999** [yandex/mocha-parallel-tests#123]
Greenkeeper brings safety & consistency to npm with real-time monitoring and automatic update testing for your dependencies. It's super convenient for OSS node projects.

Unfortunately I'm not an admin of org so I can't enable it for this repo.
https://github.com/greenkeeperio/greenkeeper/issues/324

**Comment by 1999** [comment]
@veged @dfilatov @arikon guys, can you please enable Greenkeeper for this repo?

**Comment by veged** [comment]
@1999 https://github.com/yandex/mocha-parallel-tests/settings/collaboration says that you already admin here ;-)

**Comment by 1999** [comment]
I am. The problem is that only org admins can add external integrations like this to repos afaik.

**Comment by veged** [comment]
ok, done

**Comment by 1999** [comment]
^_______^
