### ISSUE TITLE
Run test files/suites in parallel (not describes within them)

### ISSUE THREAD

**Issue by rossanthony** [yandex/mocha-parallel-tests#129]
Based on the options available today with `mocha-parallel-tests` is it possible to run a series of test files/suites in parallel? In other words; make it execute each of the describes inside each file/suite consecutively, but would run multiple test files/suites simultaneously? 

The reason I ask is that we have some describes inside certain test suites that need to happen in order otherwise they will give false negatives. But the test suites/files themselves are independent of one another and should be able to run in any order as long as the describes within them are run consecutively.

**Comment by 1999** [comment]
Currently this files/suites behaviour is not well documented. I'm working on v2 which should run all top level describes in parallel. But maybe it's worth it to add an option to run just files in parallel.

**Comment by 1999** [comment]
Sorry for silence. v2 is here, changelog should be up to date.
