### ISSUE TITLE
Opens 3 browsers per test file, even if i have  1 Testcase in  each file.

### ISSUE THREAD

**Issue by sanjayprop** [yandex/mocha-parallel-tests#130]
Don't understand the behavior,  I tried with different versions of it.Same response every time.Only execute the script in one browser per file, rest of the browsers are free.Also, driver.quit() quits only browser, which executed script.

**Comment by 1999** [comment]
@sanjayprop hey, can you please show the code of your test so we can investigate what's the issue?

**Comment by sanjayprop** [comment]
Filename: test.js

'use strict'

var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until
var test = require('selenium-webdriver/testing')
var driver = new webdriver.Builder().forBrowser('chrome').build()

 test.describe('Demo Search', function(){ 
 this.timeout(10000);
    
  test.it('should work1', function()  {   
   driver.get('http://www.google.com/')
  })

   test.after(function(){
    driver.quit()
   })
})


scripts
{
"test": "mocha-parallel-tests  ./demo/test.js",
}
