### ISSUE TITLE
Run tests recurcively 

### ISSUE THREAD

**Issue by qatechniker** [yandex/mocha-parallel-tests#132]
I am using mocha with option --recursive to run all tests in all directories. 
It does not work with mocha-parallel-test

my command looks like: ./node_modules/.bin/mocha-parallel-tests --reporter mocha-multi-reporters --max-parallel=1 --timeout=12000 -- recursive ./dist-rest/src
I am getting 
AssertionError [ERR_ASSERTION]: No test files found

Is it possible to fix it? Or let me know what I am doing wrong

Thanks in advance

**Comment by 1999** [comment]
@qatechniker can you please try that with the latest (2.0.0) version of `mocha-parallel-tests`?

**Comment by qatechniker** [comment]
@1999 works now, thanks!
