### ISSUE TITLE
mocha-parallel-tests run prints tests log after they all ended

### ISSUE THREAD

**Issue by k03mad** [yandex/mocha-parallel-tests#145]
"mocha": "5.2.0",
"mocha-parallel-tests": "2.0.0"

> ls tests
`test-01.js test-02.js`

> cat tests/test-01.js 
```js
const assert = require('assert');

describe('1 describe', () => {
    it('1 it', () => {
        console.log(1);
        assert(true);
    });
});
```

> cat tests/test-02.js 
```js
const assert = require('assert');

const nowWait = ms => {
    return new Promise(resolve => {
        setTimeout(resolve, ms);
    });
};

describe('2 describe', () => {
    it('2 it', async () => {
        await nowWait(10000);
        console.log(2);
        assert(true);
    });
});
```

**mocha prints:** 
```
1 describe
1
1 it
2 describe
```
_wait 10s_
```
2
2 it
```
**mocha-parallel-tests v2 prints:** 
_wait 10s_
```
1 describe
1
1 it
2 describe
2
2 it
```
**mocha-parallel-tests v1 prints:** 
```
1 describe
1
1 it
```
_wait 10s_
```
2 describe
2
2 it
```

**Comment by k03mad** [comment]
Если тестов много — непонятно, что происходит и происходит ли вообще.
В v1 тесты уже можно было начать разгребать, т.к. были видны все падения до конца тестов, либо остановить, если что-то пошло не так.

**Comment by 1999** [comment]
Про непонятно что происходит - это можно поправить. За это сейчас отвечает TaskManager:
https://github.com/yandex/mocha-parallel-tests/blob/master/src/main/mocha.ts#L96
https://github.com/yandex/mocha-parallel-tests/blob/master/src/main/task-manager.ts

Просто сейчас его метод run() возвращает промис, после ресолва которого начинается вывод чего-то репортерами. Можно это исправить, используя его как EventEmitter. Сможешь или я сам? @k03mad

**Comment by k03mad** [comment]
Ok, попробую на днях

**Comment by k03mad** [comment]
@1999 не выходит слон

промис выпилить — не сложно оказалось https://github.com/yandex/mocha-parallel-tests/pull/151
но дальше упираюсь в раннер, нужно как-то только прошедший тест вывести в консоль, через setTestResults, видимо, но там начинает падать всё подряд в общем... :)

я сдаюсь

**Comment by 1999** [comment]
Хм, ну, выпилить - это не главная задача ведь :) Но начал ты в правильном направлении.
Смотри, во-первых чего у нас должно получиться:

1) TaskManager уже сам по себе EventEmitter, то есть нам нужно просто эмиттить нужные события в нужное время. Сейчас эмиттятся `processingFinished` и `end`. Этого на самом деле уже достаточно. Эмиттить `runFinished` вряд ли нужно, поскольку уже есть 'end'.
2) Нужно продумать как ты хотел бы пользоваться TaskManager'ом снаружи. Мне навскидку нужны события `taskFinished` с результатами работы таска (результаты вытаскивает [эта](https://github.com/k03mad/mocha-parallel-tests/blob/master/src/main/task-manager.ts#L43) функция) и событие `end`. После каждого `taskFinished` я бы отсылал соответствующие события в src/main/runner. После `end` я бы эмиттил `suite end` и `end` (https://github.com/k03mad/mocha-parallel-tests/blob/master/src/main/runner.ts#L35).
3) `end` уже эмиттится, то есть этого достаточно. А вот `processingFinished` - слишком внутреннее событие. Я бы в его обработчике уже эмиттил `taskFinished` с нужными данными для того, что я выше описал.

Что скажешь?

**Comment by k03mad** [comment]
2. taskFinished — ок, я правда пробовал вытащить processingFinished наружу и подписываться на него. onFinishedProcessing переписывал, потому что там тогда возвращается не массив, ибо таск один, и промис резолвить не надо. Проблема именно в том, чтобы результаты собственно вывести.

ts — отдельная боль... :)

Попробую ещё.

**Comment by 1999** [comment]
Если тебе больно дебажить, вот два лайфхака с TS:

1) `ts-node src/bin/cli.ts <file.spec.js>` - запускает тесты как будто `mocha-parallel-tests <file.spec.js>`, только тебе не надо его перекомпиливать
2) `node -r ts-node/register --inspect-brk dist/bin/cli.js <file.spec.js>` - запускает ноду в режиме пошаговой отладки и ставит на паузу. Отладчик в chrome://inspect можно открыть

**Comment by k03mad** [comment]
Намудрил с PR, открыл новый: https://github.com/yandex/mocha-parallel-tests/pull/152
Хм, даже работает.

**Comment by k03mad** [comment]
@1999 🎁 

Правки и тест: https://github.com/yandex/mocha-parallel-tests/pull/154
Тест проверил до правок и после.
