### ISSUE TITLE
When run mocha-parallel-tests 2.0.2 get SyntaxError

### ISSUE THREAD

**Issue by megolee** [yandex/mocha-parallel-tests#161]
env: Mac + mocha-parallel-tests 2.0.2 + mocha 3.5.3
command: mocha-parallel-tests --reporter mochawesome --max-parallel 10 --retry 1 ./Test/Login

result: `async startTaskProcessing(task) {
          ^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/jenkins/workspace/Automation/node_modules/mocha-parallel-tests/dist/main/mocha.js:9:24)`

**Comment by 1999** [comment]
Hey @megolee, thanks for posting the issue. First of all I believe you're using the old version of mocha-parallel-tests: `--retry` option is not supported in the latest mocha-parallel-tests. Second: if you run this code with `mocha` does it work?

**Comment by megolee** [comment]
@1999 Thanks for your response :)

First: I still got the same error when I removed --retry option with command -> mocha-parallel-tests --reporter mochawesome --max-parallel 10 ./Test/Login

Second: mocha works for me. With command mocha --reporter mochawesome  ./Test/Login

When run npm list -g -depth=0, I get below

/usr/lib
├── macaca-chrome@1.0.7
├── macaca-cli@2.1.2
├── mocha@5.2.0
├── mocha-parallel-tests@2.0.1
├── mocha-simple-html-reporter@1.1.0
├── mochawesome@3.0.2
└── npm@3.10.10

**Comment by 1999** [comment]
I think I know what's the issue: you're probably using node version which is less than 8, while mocha-parallel-tests supports only node >= 8

**Comment by megolee** [comment]
@1999 You are right. When I upgrade my node >=8 , it works for me. Thank you.

Since you said mocha-parallel-tests not support --retry option, and is there any other option can replace the --retry?

**Comment by alex20465** [comment]
@1999 To support all node versions just change the tsconfig:

```
    "target": "esnext"
```

To

```
    "target": "es5"
```

**Comment by 1999** [comment]
@alex20465 that's not the only thing. Actually, the idea is we don't want to support the old versions of node, so the minimum is LTS which is 8. Also, async/await performance is much better starting from version 8 ¯\_(ツ)_/¯

**Comment by 1999** [comment]
@megolee I think what you're looking for is mocha `--retries` option. It is supported by `mocha-parallel-tests` as well.

**Comment by alex20465** [comment]
Anyway I created a fork ES6 version of this package:

```
npm install mocha-parallel-tests-es6 
```

works fine.

**Comment by 1999** [comment]
@alex20465 it would be also great if you put a link somewhere to the README of the forked project about the `mocha-parallel-tests`.
