### ISSUE TITLE
Tests stop after uncaught first exception.

### ISSUE THREAD

**Issue by tosbaha** [yandex/mocha-parallel-tests#172]
I have multiple test files. I want to run them in parallel programmatically. If one of the test files fail with Uncaught exception, testing stops. I checked the source code and saw that you are using process.exit after `Uncaught exception` I tried to set `bail:false` but it didn't change anything. 

TLDR; I want to run all test files in parallel and get a report at the end even if one the tests are failed/crashed.

**Comment by 1999** [comment]
@tosbaha thank you for posting the issue. That sounds weird, I will take a look soon.

**Comment by 1999** [comment]
The newly published `mocha-parallel-tests=2.0.3` has the fix.

**Comment by 1999** [comment]
@tosbaha not a problem. Unfortunately I can't reproduce your issue: in my case I can see that the test finishes with an "end" event:
```js
describe('suite', function () {
    it('throw exception immediately', function () {
        throw new Error('foo');
    });

    // eslint-disable-next-line no-unused-vars
    it('throw exception in setTimeout', function (done) {
        setTimeout(() => {
            throw new Error('foo');
        }, 100);
    });

    it('should pass', () => {
        // eslint-disable-next-line no-unused-vars
        const a = 2;
    });

    it('throw exception in promise', () => {
        return new Promise(() => {
            throw new Error('foo');
        });
    });

    it('require unknown package', () => {
        require('packagedoesnotexist');
    });

    it('should pass', () => {
        // eslint-disable-next-line no-unused-vars
        const a = 2;
    });
});
```

![image](https://user-images.githubusercontent.com/73191/41849250-920e6ec0-78c3-11e8-840b-29df4087be1a.png)

Can you create a gist/repo so that I could reproduce it?

**Comment by tosbaha** [comment]
For me it is giving me an error. Here is my test setup.

**1.test.js**

```javascript
const abcd = require('thisdoesntexist');

describe('First Test:', function() {
    it('should crash', function (done) {
        done();
    });

});
```

**2.test.js**

```javascript

describe('Second Test', function() {

    it('case 2', function (done) {
        setTimeout(() => {
           throw new Error('foo');
            }, 100);
        });
});
```

**3.test.js**

```javascript
describe('Third Test:', function() {

    it('should work', function (done) {
        console.log('Third Test OK');
        done();
    });

});
```

**4.test.js**

```javascript
describe('Fourth Test:', function() {

    it('should work too', function (done) {
        console.log('Fourth Test OK');
        done();
    });

});
```

Testing Code
===

```javascript
const  Mocha = require('mocha-parallel-tests').default;
const glob = require('glob-promise');

const mocha = new Mocha({
    bail:false,
    reporter: 'mochawesome',
    reporterOptions: {
        reportTitle: 'My Tests',
        reportPageTitle: 'Health Check',
        json: true,
        html: true,
        code: false,
        //    quiet: true
    }
});

class HealthCheck {

    async getMocha() {
        const specs = await glob('./testfolder/*.js', {absolute: true});
        console.log(specs);
        specs.map(spec => {
            mocha.addFile(spec);
        });
        mocha.suite.timeout(60000);
        return mocha;
    }

    async checkIt() {

        return new Promise(async (resolve) => {
            const mocha = await this.getMocha();
            const runner = await mocha.run();

            let testError = null;
            runner.on('end', () => {
                console.log('Final end!');

                if (testError) console.error(testError.err);
                resolve();
            });

        });

    }
}

(async() => {
    try {
        const health = new HealthCheck();
        const result = await health.checkIt();
        console.log('Result: ' + result);
    } catch (e) {
        console.log('Error: ' + e);
    }
})();

```

PS: I tested with or without mochawesome. It always crashes and stop processing other test files.

**Comment by 1999** [comment]
This is pretty expected: if you run your code with `mocha` it will throw exception here as well. At least that happens to me on mocha@5. So `mocha-parallel-tests` does nothing new here 🤷‍♂️

![image](https://user-images.githubusercontent.com/73191/41851985-192aca62-78cd-11e8-9248-28b6cc368e8f.png)

Neat pick: in your code `const runner = await mocha.run()` await is not needed: `mocha.run()` immediately returns a runner object.

**Comment by tosbaha** [comment]
Thanks again for the feedback. I thought maybe there was a way to catch all kind of errors. `Domain` maybe? PS: Thanks for your comment about for `mocha.run()` Keep up the good work. 👍

**Comment by 1999** [comment]
Cheers, mate 😎
Domains are deprecated, so not sure. Ideally these kind of errors are fatal which means that ideally you need to fix them asap. Otherwise you'll have a feeling like "of my tests is failing so I need to fix it". There's also mocha's `--allow-uncaught` option, I actually didn't play with it so maybe it can help.
