### ISSUE TITLE
Performance comparison between `mocha.parallel`

### ISSUE THREAD

**Issue by amilajack** [yandex/mocha-parallel-tests#52]
I'm trying to find the fastest mocha 'parallelizing' library. It would be useful if the performance if this library could be compared to those of others.

**Comment by 1999** [comment]
Thank you for posting issue!

I'm not sure about the performance comparison, but from what I see, `mocha.parallel` changes the way you write tests: it adds its own API. At the same time `mocha-parallel-tests` has better test coverage because it has been developing all this time with TDD.

But I will try to make some perfomance comparison soon.

**Comment by F1LT3R** [comment]
I believe the performance increase for `mocha.parallel` is that is uses Bluebird, which implements Promises as compiled machine-code, rather than it running on parallel threads. In theory `mocha-parallel-tests` could do the same thing to boost performance (if it's not already).

**Comment by F1LT3R** [comment]
You could also bak threading into the core: https://www.npmjs.com/package/threads

Actually if `mocha-parallel-tests` used threads, it would be a huge, huge, massive win. (That and it not swallowing console logs and exceptions.)

**Comment by 1999** [comment]
> uses Bluebird

Hm... Well, mocha-parallel-tests is not using promises at all, so I don't know if bluebird usage is good or bad. As for threads: yes, mocha-parallel-tests is currently running inside one thread, but there's an issue to investigate running inside multiple threads: #66.

Right now I would say that using multiple threads will result in worse performance because of threads creation cost, but #66 is definitely better place to discuss this.

**Comment by amilajack** [comment]
I think it depends on the kind of tests that are being run. A lot of my tests make HTTP requests and start up electron. In these kinds of situations, adding thread support could really help out. But for simple unit test assertions, threads would be a drawback.

**Comment by F1LT3R** [comment]
Good points. 

I also agree it depends on the kinds of tests being run.

It could mean worse performance for basic unit testing. When I run threaded code in Node, I stop seeing a direct benefit after 4-5 threads on a Mac Book Pro. But if the code I was running was much quicker, I understand why you would see the thread startup/teardown costs.

And... I think you would also have to be writing code that would instantiate appropriately if testing code from `require('im-a-singleton')` with threads. As far as I'm aware, by-and-large, I don't think people are writing their modules that way.

As @amilajack points out, service based tests could really benefit from threading. Also testing functions that are running heavier calculations would benefit from threads (more my use case).

Perhaps a new testing library specifically for threaded testing would be more relevant and should be designed from the ground up. I suppose I was hoping as Mocha is a nice syntax, that there was something out there already. :)

**Comment by amilajack** [comment]
> Perhaps a new testing library specifically for threaded testing

Not sure if a new library is needed. How about a config option through a flag:

```
./node_modules/.bin/mocha-parallel-tests --threads=true **/*.js
```

Setting to `true` would automatically scale the tests to how many cores the CPU has. By default, this should be off (`--threads=false`).

**Comment by 1999** [comment]
> As @amilajack points out, service based tests could really benefit from threading

Can't agree. Service-based tests are async and don't depend heavily on CPU, so mocha-parallel-test's one thread should be okay

< Also testing functions that are running heavier calculations would benefit from threads (more my use case).

Totally agree

> How about a config option through a flag

Sounds good.

**Comment by amilajack** [comment]
Do you guys know a good library that makes multithreading easy in node?

**Comment by F1LT3R** [comment]
> @1999: Can't agree.

I see your point. 

> @amilajack: Do you guys know a good library that makes multithreading easy in node?

- `cluster` https://www.sitepoint.com/how-to-create-a-node-js-cluster-for-speeding-up-your-apps/
- `web-worker-threads` https://www.npmjs.com/package/webworker-threads

**Comment by 1999** [comment]
@amilajack what's wrong with native child_process module?

**Comment by amilajack** [comment]
There are a number of limitations with mutithreaded javascript. But I think we should try using `child_process` before we try using libraries.

**Comment by 1999** [comment]
Not sure about the performance comparison but I finally made it:
https://github.com/yandex/mocha-parallel-tests/wiki/Comparison-with-mocha.parallel
https://github.com/yandex/mocha-parallel-tests#comparison-with-mochaparallel
