### ISSUE TITLE
Using console.log in custom command out of test file

### ISSUE THREAD

**Issue by k03mad** [yandex/mocha-parallel-tests#65]
Hello!

I have a custom command which print current url to console.
Command adds at file which requires from test-file.

Then I run the tests, all console.logs prints before first test, not in each test structure.
Custom command:

``` javascript
client.addCommand('printUrl', (indent) => {
    let space = '';
    indent = indent || 4;

    return client.getUrl().then(url => {
        for (let i = 0; i < indent; i++) {
            space += ' ';
        }
        console.log(`${space}➜ ${url}`);

        return url;
    });
});
```

**Comment by k03mad** [comment]
Сейчас юзаю хуку beforeEach(), в которой проверяю изменился ли урл — если да, вывожу его в консоль:

````javascript
beforeEach(() => {
    return client.getUrl().then(url => {

        if (url !== currentUrl) {
            return client.getTitle().then(title => {
                console.log(`\n➜ ${colors.blue.underline(url)} (${colors.white(title)})\n`);
            });
        }

        currentUrl = url;
    });
});
````

Хуки подключаются ко всем тестам из отдельного модуля:
````javascript
require('../hooks')(browser);
````

При запуске тестов в консольку выводится куча урлов.
Ожидание: урлы выводятся в структуре каждого теста.

**Comment by 1999** [comment]
@k03mad у тебя нет времени посмотреть эту багу самому?

**Comment by k03mad** [comment]
Со свободным временем совсем беда, возможно доберусь как-нибудь.
Баг не критичный — больше никто не отписался, а нам, вроде, уже и не надо...)

**Comment by 1999** [comment]
mocha-parallel-tests@2 runs each file in parallel, so this issue should now be fixed as well.
