### ISSUE TITLE
Parallelization across threads

### ISSUE THREAD

**Issue by amilajack** [yandex/mocha-parallel-tests#66]
Right now the parallelization benefits that I get from using this module aren't very significant. What do you think about parallelizing the work across threads?

**Comment by 1999** [comment]
Thinking of it right now :)

**Comment by amilajack** [comment]
Also, ideally, this project would feature some benchmarks so that we can know about performance regressions.

**Comment by 1999** [comment]
v2.0.0 is all about this.
