### ISSUE TITLE
Do not retry all file if one of the first level describe is failed

### ISSUE THREAD

**Issue by k03mad** [yandex/mocha-parallel-tests#77]
1. В файле три дескрайба на первом уровне
2. Они выполняются параллельно
3. Если один из них упадёт, то сработает --retry и перезапустит весь файл

Чем плохо: два других дескрайба, рядом с упавшим, выполнятся ещё столько же раз, сколько установлен --retry, даже если с ними всё в порядке.

**Comment by 1999** [comment]
2a7d0c590c8ed0dd8587192f2921710d9ee58f5a

**Comment by k03mad** [comment]
wow 👍
