### ISSUE TITLE
Doesn't work with --no-exit

### ISSUE THREAD

**Issue by k03mad** [yandex/mocha-parallel-tests#85]
> --no-exit
> require a clean shutdown of the event loop: mocha will not call process.exit

В своём кастомном раннере на событие 'end' повесил отправку сообщений в слак.
Чтобы отправка работала использую --no-exit, иначе сообщение не отправляется.
https://github.com/mochajs/mocha/issues/2541

С мокой работает, с параллельной мокой нет.
Чтобы воспроизвести: сделал ветку issueMPT и два скрипта для проверки:

npm run issue-m --target=www --slack=test
npm run issue-mpt --target=www --slack=test

issue-m — мока
issue-mpt — параллельная мока
test — название канала **(подставить свой канал для проверки)**

**Comment by 1999** [comment]
cc @mmotkina

**Comment by 1999** [comment]
Занятная штука. Я по коду моки нашел только упоминание этой опции и тест, связанный с ней, но не собственно сам код, хотя он там несомненно есть. Предполагаю, что если просто убрать `process.exit` из кода mpt, то будет похожее поведение, впрочем надо смотреть и писать код/тесты.

**Comment by 1999** [comment]
@k03mad сейчас у тебя есть вариант для обхода этого бага: форкать процесс (`child_process.fork`) на `end`-событие раннера. Таким образом у тебя завершится процесс mpt, но отфорканный процесс, в котором ты и будешь отсылать в слак что тебе надо, будет продолжать работать. Когда Маша (или я) починят этот баг, ты сможешь отказаться от этого костыля.

**Comment by 1999** [comment]
@k03mad впрочем если бы и ты подключился, было бы прекрасно вообще.

**Comment by k03mad** [comment]
> форкать процесс (child_process.fork) на end-событие раннера
👍 спасибо, посмотрю в эту сторону. 

> впрочем если бы и ты подключился, было бы прекрасно вообще.
Со временем код mpt мне всё меньше кажется неким рокет сайнс, но пока ещё не до конца)
Но локально покопаюсь, да.

**Comment by 1999** [comment]
Если будешь готов, напиши тут, я переассайню таск на тебя.

**Comment by k03mad** [comment]
Застрял.

Вот тут https://github.com/veged/mocha-parallel-tests/blob/master/bin/mocha-parallel-tests#L17, судя по https://github.com/mochajs/mocha/pull/1059/commits/8aafaa4953261e9443d4440b042f43541e14bed0 должно было помочь:

```javascript
binHelper(argv).then((failsOccured) => {
    // wait for reporter to finish its operations
    // exit with code equal to number of failed tests
    process.nextTick(() => {
        if (argv._.exit) {
            process.exit(failsOccured);
        } else {
            // if --no-exit argv is present wait for exit event
            process.on('exit', process.exit(failsOccured));
        }
    });
});
```

**Comment by 1999** [comment]
1) Зачем там nextTick?
2) `argv._.noExit` может?

**Comment by k03mad** [comment]
2) Условие точно верное:

```
> cross-conf-env mocha-parallel-tests --compilers js:babel-register --reporter npm_package_config_reporter --no-exit --timeout npm_package_config_timeout_frontend --slow npm_package_config_slow_frontend tests/frontend/kp1/npm_config_testcase.js

{ _: 
   [ '/usr/local/Cellar/node/7.0.0/bin/node',
     '/Users/kirill-m/git/kinopoisk-regression/node_modules/.bin/mocha-parallel-tests',
     'tests/frontend/kp1/kinopoisk-108.js' ],
  compilers: 'js:babel-register',
  reporter: 'reporters/slack-spec',
  exit: false,
  timeout: 300000,
  slow: 30000,
  '$0': 'node_modules/.bin/mocha-parallel-tests' }
```

**Comment by k03mad** [comment]
1) Он же там по умолчанию есть

**Comment by 1999** [comment]
Кул, тогда давай тест и PR :)

**Comment by k03mad** [comment]
> Застрял.

Означает, что это не помогло :) 
В слак сообщение в on 'end' репортера всё равно не уходит.

**Comment by 1999** [comment]
![](https://dl.dropboxusercontent.com/u/582455/pics/what-dolphin-thinks-about-that.jpg)

**Comment by k03mad** [comment]
Я подтупил.
Не ```argv._.exit```, a ```argv.exit```

**Comment by k03mad** [comment]
https://github.com/veged/mocha-parallel-tests/pull/86
Тест придумаю, как разберусь, как они тут работают

**Comment by 1999** [comment]
#87 87
