### ISSUE TITLE
large number of describe()'s

### ISSUE THREAD

**Issue by kolontsov** [yandex/mocha-parallel-tests#89]
It seems when number of parallel test grows, the execution time starts growing:

```
$ cat parallel.js
function add_test(index){
    describe('Test suite '+index, function () {
        for (let i=0; i<10; i++)
        {
            it('it#'+i, function (done) {
                setTimeout(done, 1000);
            });
        }
    });
}

for (let i=0; i<1000; i++)
    add_test(i);

$ time mocha-parallel-tests parallel.js
...
10000 passing (2m)
mocha-parallel-tests parallel.js  121.04s user 1.22s system 92% cpu 2:11.54 total
```

Is it expected behaviour? I expected about 10-15 second max. Thanks for possible ideas.

**Comment by 1999** [comment]
10 seconds would be super performance yet it's impossible due to own mocha-parallel-tests and mocha's own running code. But 20 seconds should be ok for this, definitely not 2 minutes. Needs investigation @k03mad

**Comment by k03mad** [comment]
Something strange here. Execution time starts growing with increasing 'it' amount. 

```javascript
for (let i = 0; i < 1000; i++) {
    describe(`Test suite #${i}`, () => {
        for (let j = 0; j < process.env.IT; j++) {
            it(`it #${j}`, () => {});
        }
    });
}
```

IT = 1: 1 000 passing (real 14.41s)
IT = 5: 5 000 passing (real 37.69s)
IT = 10: 10 000 passing (real 89.05s)

**Comment by 1999** [comment]
Could you run this test with original `mocha`?

**Comment by k03mad** [comment]
**mocha**, IT = 10: 10 000 passing (real **1.42**s)
**mocha-parallel-tests**, IT = 10: 10 000 passing (real **76.37**s)

**Comment by 1999** [comment]
Seems like smth is totally broken. @k03mad could you fix that?

**Comment by k03mad** [comment]
I can try when I find some time for it, but now I don't even have ideas what is going wrong.

**Comment by kolontsov** [comment]
It seems that all time is spent in this line: https://github.com/yandex/mocha-parallel-tests/blob/master/lib/watcher.js#L209

Once all tests are prepared, they run fast.

**Comment by kolontsov** [comment]
Any updates on this issue? I understand that due mocha-parallel-test nature, the original loop above actually executes `it()` statement `1000*1000*process.env.IT` times (and not `1000*process.env.IT` times, as standalone mocha), but why it takes so long? May be some mocha internal structures are not cleared between executions, so it grows and become slow?

**Comment by 1999** [comment]
Sorry, didn't have time for that in the last month.
@k03mad maybe you will take ownership on this issue?

**Comment by k03mad** [comment]
@1999 

I think you overestimate my js-skills (:

I made several attempts today. 
...and it's too rocket science for me right now.

**Comment by 1999** [comment]
Только решая сложные задачи сможешь расти над собой :) @k03mad 
Попробуй еще раз в свободное время.

**Comment by 1999** [comment]
@kolontsov can you try mocha-parallel-tests@v2 and say if it's still a case for you?

**Comment by kolontsov** [comment]
@1999 thanks for mention, I'll test and report.

**Comment by 1999** [comment]
Closing as inactive.
