### ISSUE TITLE
--recursive flag not working

### ISSUE THREAD

**Issue by jankcat** [yandex/mocha-parallel-tests#94]
Hello,

It seems that the recursive flag from mocha is not working in this module.

My structure:
Project Folder
-- test (default mocha folder)
---- rootHooks.js
---- Folder 1
------ page1.js
------ page2.js
---- Folder 2
------ page1.js
------ page2.js
------ page3.js

For Mocha, I usually can run the following: "mocha --require babel-register --recursive", which tells mocha to recursively run in each folder, and defaults to the folder "test"

I have tried the flag with mocha-parallel-tests, as well as the following, with no luck:
mocha-parallel-tests --max-parallel 4 --require babel-register --recursive test/
mocha-parallel-tests --max-parallel 4 --require babel-register --recursive
mocha-parallel-tests --max-parallel 4 --require babel-register --recursive test/**/*.js
mocha-parallel-tests --max-parallel 4 --require babel-register test/**/*.js
mocha-parallel-tests --max-parallel 4 --require babel-register --recursive **/*.js

None of these combos will run my subfolder tests, but still run the root hooks in the test folder. It works for mocha, not for mocha-parallel-tests.

Any ideas? Am I doing something wrong/missing something?

**Comment by 1999** [comment]
It seems like this is an error. Thank you for posting it. Will take a look soon (2-3 days).

**Comment by 1999** [comment]
Seems strange because I can't reproduce your issue in my PR: https://github.com/yandex/mocha-parallel-tests/pull/95
Could you please check the PR or provide the code from your tests which is not running?

**Comment by 1999** [comment]
@jankcat ping

**Comment by jankcat** [comment]
Sorry. I've been out of the office. I'll be back next week and can try again then.

**Comment by 1999** [comment]
@jankcat one more ping :)

**Comment by jankcat** [comment]
I threw a repo up here with the issue, as I am still seeing it: [here](https://github.com/jankcat/mocha-parallel-example-issue)

You can see the commands I am running [here.](https://github.com/jankcat/mocha-parallel-example-issue/blob/master/package.json#L6)

And screenshots [here.](https://github.com/jankcat/mocha-parallel-example-issue/tree/master/docs)

1. Running the command to run all the tests in a folder does not work as it does in mocha, instead it complains that no tests exist.
2. Specifying a subfolder of tests works, but the root hooks (before all, after all) do not run, even when explicitly added to the command (see the single area and two area tests, as well as the sub area test in the example repo)

**Comment by 1999** [comment]
Sorry, now delay is from my side. I can see, will try to fix these.

**Comment by jankcat** [comment]
Ah okay. I dont remember what my use case was (oops).

Thanks! The cats are not mine, but I do have 3 others that didnt make the pic.
