### ISSUE TITLE
--reporter-options flag is not working properly

### ISSUE THREAD

**Issue by Dante1313** [yandex/mocha-parallel-tests#96]
Hello,

I trying to use different type of reporters( mocha: xunit, custom: mochawesome, mocha-junit-reporter ) with flag --reporter-options, but seems that this flag is not working properly.  

When I run tests by mocha — all works fine. 

Example of commands:
- mocha my-test --reporter xunit --reporter-options output=reports/report-mocha.xml
- mocha my-test --reporter mocha-junit-reporter --reporter-options mochaFile=reports/report-mocha.xml
- mocha my-test --reporter mochawesome --reporter-options reportDir=reports,reportFilename=report-mocha

If I run the commands mentioned above with mocha-parallel-tests instead of mocha, the tests are performed successfully, but the report file is not created.

Versions:

- node v6.9.1
- mocha v2.5.3
- mocha-parallel-tests v1.2.5
- mocha-junit-reporter v1.13.0
- mochawesome v2.0.2

**Comment by 1999** [comment]
Thank you. Will take a look on these holidays.

**Comment by 1999** [comment]
Unfortunately this is the same issue as #80. Bad news here is that this issue is at this time really hard to solve.

**Comment by 1999** [comment]
Reporters behaviour is fixed in mocha-parallel-tests@2
